-- Weekly review reports: portfolio week-over-week numbers + AI self-review
-- (report_md) and a raw-data handover document for external LLMs (handover_md).
-- One row per generated review; stats holds structured aggregates (jsonb) so
-- future features can chart without re-parsing markdown. Generated by the
-- backend (service role); web reads only.
create table if not exists public.weekly_reviews (
    id           bigserial primary key,
    week_start   date         not null,
    week_end     date         not null,
    report_md    text         not null,
    handover_md  text         not null default '',
    stats        jsonb,
    model        varchar(100),
    emailed      boolean      not null default false,
    created_at   timestamptz  not null default now()
);
create index if not exists ix_weekly_reviews_week on public.weekly_reviews (week_end desc);

alter table public.weekly_reviews enable row level security;
drop policy if exists read_weekly_reviews on public.weekly_reviews;
create policy read_weekly_reviews on public.weekly_reviews
    for select to authenticated using (true);

insert into public.schema_migrations (version, name)
values ('023', '023_weekly_reviews') on conflict do nothing;
